// Meridian v2 — paper trading / signal tracking
// Closes the loop: signals generated by the screener get logged and marked to
// market, so over time you can see whether your own screens actually work.

import { all, one, run } from '../db.js';
import { getBars } from '../db.js';

export function openTrade({ symbol, entryPrice, qty = 1, source = 'manual', signal = null, thesis = null, target = null, stop = null }) {
  const date = new Date().toISOString().slice(0, 10);
  run(`INSERT INTO paper_trades (symbol, source, signal, thesis, entry_date, entry_price, qty, status, target, stop, created_at)
       VALUES (?,?,?,?,?,?,?, 'open', ?,?,?)`,
      symbol, source, signal, thesis, date, entryPrice, qty, target, stop, Date.now());
  return one('SELECT * FROM paper_trades ORDER BY id DESC LIMIT 1');
}

export function closeTrade(id, exitPrice) {
  const date = new Date().toISOString().slice(0, 10);
  run(`UPDATE paper_trades SET exit_date = ?, exit_price = ?, status = 'closed' WHERE id = ?`,
      date, exitPrice, id);
  return one('SELECT * FROM paper_trades WHERE id = ?', id);
}

/** Mark open trades to market and auto-close any that hit target or stop. */
export function markToMarket(prices) {
  const open = all("SELECT * FROM paper_trades WHERE status = 'open'");
  const closedNow = [];
  for (const t of open) {
    const px = prices[t.symbol]?.price;
    if (px == null) continue;
    if (t.stop != null && px <= t.stop) { closeTrade(t.id, px); closedNow.push({ ...t, reason: 'stop', exit: px }); }
    else if (t.target != null && px >= t.target) { closeTrade(t.id, px); closedNow.push({ ...t, reason: 'target', exit: px }); }
  }
  return closedNow;
}

export function performance(prices = {}) {
  const trades = all('SELECT * FROM paper_trades ORDER BY entry_date DESC');
  const enriched = trades.map(t => {
    const exit = t.status === 'closed' ? t.exit_price : (prices[t.symbol]?.price ?? t.entry_price);
    const ret = t.entry_price ? (exit / t.entry_price - 1) * 100 : 0;
    const days = Math.round((Date.parse(t.exit_date ?? new Date().toISOString().slice(0, 10)) - Date.parse(t.entry_date)) / 86400000);
    return {
      id: t.id, symbol: t.symbol, source: t.source, signal: t.signal, thesis: t.thesis,
      entryDate: t.entry_date, entryPrice: t.entry_price,
      exitDate: t.exit_date, exitPrice: t.status === 'closed' ? t.exit_price : null,
      markPrice: +exit.toFixed(4),
      returnPct: +ret.toFixed(2),
      holdingDays: days, status: t.status,
      target: t.target, stop: t.stop,
    };
  });

  const closed = enriched.filter(t => t.status === 'closed');
  const wins = closed.filter(t => t.returnPct > 0);
  const bySource = {};
  for (const t of closed) {
    const s = (bySource[t.source ||= 'manual'] ||= { source: t.source, n: 0, total: 0, wins: 0 });
    s.n++; s.total += t.returnPct; if (t.returnPct > 0) s.wins++;
  }

  return {
    trades: enriched,
    open: enriched.filter(t => t.status === 'open').length,
    closed: closed.length,
    winRate: closed.length ? +(wins.length / closed.length * 100).toFixed(1) : null,
    averageReturn: closed.length ? +(closed.reduce((a, t) => a + t.returnPct, 0) / closed.length).toFixed(2) : null,
    bestTrade: closed.length ? closed.reduce((a, t) => (!a || t.returnPct > a.returnPct ? t : a), null) : null,
    worstTrade: closed.length ? closed.reduce((a, t) => (!a || t.returnPct < a.returnPct ? t : a), null) : null,
    bySource: Object.values(bySource).map(s => ({
      source: s.source, trades: s.n,
      averageReturn: +(s.total / s.n).toFixed(2),
      winRate: +(s.wins / s.n * 100).toFixed(1),
    })),
  };
}

export function listTrades() { return all('SELECT * FROM paper_trades ORDER BY id DESC'); }
export function deleteTrade(id) { run('DELETE FROM paper_trades WHERE id = ?', id); }
